apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: ssuai-backend
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: ssuai-backend
      useAnnotations: true
