apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: ssuai
    app.kubernetes.io/part-of: ssuai
    environment: prod
  annotations:
    argocd.argoproj.io/sync-wave: "0"
